name: Docker Flask Image CI/CD

on:
  push:
    paths:
      - backend/AI/**  # Only run workflow when changes are made to the backend/AI directory
      - .github/workflows/deploy-flask.yml
    branches:
      - main

defaults:
  run:
    working-directory: backend/AI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/kisia-project-backend:ai .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/kisia-project-backend:ai

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Pulling AI image from Docker..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/kisia-project-backend:ai
            docker stop ai || true
            docker rm ai || true
            docker run -d --log-driver=syslog -p 8080:8080 --network app-network --env-file .env --name ai ${{ secrets.DOCKER_USERNAME }}/kisia-project-backend:ai
            echo "AI docker image has been deployed successfully."
            docker image prune -a -f

            